### ISSUE TITLE
Inclusion on Stackage

### ISSUE THREAD

**Issue by cies** [yusent/yesod-auth-bcryptdb#1]
Nice lib, works like a charm :) Please consider including it on Stackage. It will give you (and other users of the lib) some guarantees wrt it building together with the other packages.

**Comment by yusent** [comment]
I created a PR: fpco/stackage#3324.

Thanks for your feedback :)

**Comment by yusent** [comment]
Thanks for your feedback :)

**Comment by yusent** [comment]
Done: https://github.com/fpco/stackage/commit/f948e83808503db26e4a16e2312b5909dee81b78
